### ISSUE TITLE
GetEntries -bydate por query opt

### ISSUE THREAD

**Issue by diegoloiacono** [diegoloiacono/compartir_enlaces#12]
en el endpoint de ver entries por fecha pedís autorización, debería de ser público. en el postman pasáis date como query param, pero el endpoint lo recibe por path param. este endpoint sería innecesario, podríais hacer el el get entries normal, pueda recibir opcionalmente un query param date, y si lo recibe, que filtre por fecha

**Comment by guillelp1996** [comment]
resolve  `e482514` guille's branch
